### ISSUE TITLE
Gorilla (?) does not set the correct mime types

### ISSUE THREAD

**Issue by VipeOut23** [wtfd-tech/wtfd#46]
Firefox refuses to load bundle.js when `X-Content-Type-Options: nosniff` 
-> [Info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)

```
The resource from “http://localhost:8080/static/bundle.js” was blocked due to MIME type (“text/plain”) mismatch
```

**Comment by ragon000** [comment]
Can you confirm bundle.js exists?

**Comment by VipeOut23** [comment]
Oh, my bad. I did sth. wrong while compiling js and didn't assume a mime type error due to missing files. Now it works how it is intended.
